### ISSUE TITLE
Error: Error setting up environment

### ISSUE THREAD

**Issue by mikemhenry** [mamba-org/provision-with-micromamba#121]
I've never seen this error before when using this action, I've copied the bit at the end:

```
   Transaction finished
  
  To activate this environment, use:
  
      $ [micro]mamba activate <environment>
  
  Or to execute a single command in this environment, use:
  
      $ [micro]mamba run -n <environment> mycommand
  
  --- Contents of /root/.bash_profile ---
  # .bash_profile
  
  # Get the aliases and functions
  if [ -f ~/.bashrc ]; then
  	. ~/.bashrc
  fi
  
  # User specific environment and startup programs
  
  PATH=$PATH:$HOME/bin
  
  export PATH
  
  
  # >>> mamba initialize >>>
  # !! Contents within this block are managed by 'mamba init' !!
  export MAMBA_EXE="/root/micromamba-bin/micromamba";
  export MAMBA_ROOT_PREFIX="/root/micromamba-root";
  __mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
  if [ $? -eq 0 ]; then
      eval "$__mamba_setup"
  else
      if [ -f "/root/micromamba-root/etc/profile.d/micromamba.sh" ]; then
          . "/root/micromamba-root/etc/profile.d/micromamba.sh"
      else
          export  PATH="/root/micromamba-root/bin:$PATH"  # extra space after export prevents interference from conda init
      fi
  fi
  unset __mamba_setup
  # <<< mamba initialize <<<
  
  set -eo pipefail; micromamba activate nnpops;
  --- End contents of /root/.bash_profile ---
  /usr/bin/bash -eo pipefail -l -c micromamba info --json
  {
      "base environment": "/root/micromamba-root",
      "channels": null,
      "curl version": "libcurl/7.88.1 OpenSSL/3.1.0 zlib/1.2.13 zstd/1.5.2 libssh2/1.10.0 nghttp2/1.52.0",
      "env location": "-",
      "environment": "None (not found)",
      "libarchive version": "libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2",
      "libmamba version": "1.4.2",
      "micromamba version": "1.4.2",
      "platform": "linux-64",
      "populated config files": null,
      "user config files": [
          "undefined/.mambarc"
      ],
      "virtual packages": [
          "__unix=0=0",
          "__linux=4.14.304=0",
          "__glibc=2.26=0",
          "__archspec=1=x86_64",
          "__cuda=11.7=0"
      ]
  }
  Error: Error setting up environment
  /actions-runner/_work/_actions/mamba-org/provision-with-micromamba/main/dist/main/index.js:67337
      throw Error('Error setting up environment')
            ^
  
  Error: Error setting up environment
      at installEnvironment (/actions-runner/_work/_actions/mamba-org/provision-with-micromamba/main/dist/main/index.js:67337:11)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async main (/actions-runner/_work/_actions/mamba-org/provision-with-micromamba/main/dist/main/index.js:67400:3)
      at async run (/actions-runner/_work/_actions/mamba-org/provision-with-micromamba/main/dist/main/index.js:67419:5)
```

This is how I am using the action: https://github.com/openmm/NNPOps/pull/100/files#diff-bd64c4de8527b7011b64ffef8a82f8ab32dae8c0ac01c59a71d4f3b28f05cfddR57-R67

And her is a link to the full build log: https://github.com/openmm/NNPOps/actions/runs/4751059677/jobs/8439836701#step:3:1

I am sure I am doing something really silly but I can't quite catch where the error is.

The output of `micromamba info` has me sus, I think that `$HOME` isn't being resolved correctly.

**Comment by mikemhenry** [comment]
That's exactly what it was, sorry for the noise!
