### ISSUE TITLE
Issue with caching for GDAL on macos instance

### ISSUE THREAD

**Issue by cheginit** [mamba-org/provision-with-micromamba#68]
I have setup `micromamba` in my [repo](https://github.com/cheginit/pygeohydro)'s GitHub Actions workflow like so:

```yaml
      - name: Setup micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ env.CONDA_ENV_FILE }}
          environment-name: ${{ env.REPO_NAME }}-tests
          extra-specs: |
            python=${{ env.PYTHON_VERSION }}
          cache-env: true
          cache-env-key: "${{runner.os}}-py${{matrix.python-version}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
```

This will create the environment successfully but when the testing begins I get this error only on the `macos` instance (`ubuntu` and `windows` don't have this issue):

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/work/pygeohydro/pygeohydro/pygeohydro/__init__.py", line 12, in <module>
    from .pygeohydro import (
  File "/Users/runner/work/pygeohydro/pygeohydro/pygeohydro/pygeohydro.py", line 17, in <module>
    import pygeoutils as geoutils
  File "/Users/runner/micromamba/envs/pygeohydro-tests/lib/python3.10/site-packages/pygeoutils/__init__.py", line 2, in <module>
    from ._utils import transform2tuple
  File "/Users/runner/micromamba/envs/pygeohydro-tests/lib/python3.10/site-packages/pygeoutils/_utils.py", line 11, in <module>
    import rasterio as rio
  File "/Users/runner/micromamba/envs/pygeohydro-tests/lib/python3.10/site-packages/rasterio/__init__.py", line 9, in <module>
    from rasterio._base import gdal_version
ImportError: dlopen(/Users/runner/micromamba/envs/pygeohydro-tests/lib/python3.10/site-packages/rasterio/_base.cpython-310-darwin.so, 2): Symbol not found: _ZSTD_compressBound
  Referenced from: /Users/runner/micromamba/envs/pygeohydro-tests/lib/libgdal.30.dylib
  Expected in: /Users/runner/micromamba/envs/pygeohydro-tests/lib/libblosc.1.dylib
 in /Users/runner/micromamba/envs/pygeohydro-tests/lib/libgdal.30.dylib
```

When I disable caching the tests run without any issue. You can check out the full logs [here](https://github.com/cheginit/pygeohydro/runs/6869723846?check_suite_focus=true).

**Comment by cheginit** [comment]
I just noticed that it fails without caching as well. But it's only related to macOS. Previously, I was using [setup-miniconda](https://github.com/conda-incubator/setup-miniconda) and things work without any issue so I am surprised that `micromamba` is not working for macOS since they both use `mamba` and `conda-forge`.

**Comment by cheginit** [comment]
I figured out the issue, it didn't have to do anything with `micromamba`. Sorry for the inconvenience.

**Comment by wolfv** [comment]
thanks for letting us know!
