### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by michaelaye** [mamba-org/provision-with-micromamba#90]
This is how I call the action:

```yaml
      uses: mamba-org/provision-with-micromamba@main
      with:
        channels: conda-forge
        environment-file: ""
        extra-specs: ""
```
and this is what i get from the runner:

```
Run mamba-org/provision-with-micromamba@main
  with:
    channels: conda-forge
    micromamba-version: latest
    channel-priority: strict
    cache-downloads: false
    cache-env: false
    log-level: warning
    installer-url: https://micro.mamba.pm/api/micromamba
    post-deinit: auto
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.6/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.6/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.6/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.6/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.6/x64/lib
  
Error: EISDIR: illegal operation on a directory, read
node:fs:723
  handleErrorFromBinding(ctx);
  ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at main (/home/runner/work/_actions/mamba-org/provision-with-micromamba/main/dist/main/index.js:64061:34)
    at run (/home/runner/work/_actions/mamba-org/provision-with-micromamba/main/dist/main/index.js:64093:11)
    at /home/runner/work/_actions/mamba-org/provision-with-micromamba/main/dist/main/index.js:64100:1
    at /home/runner/work/_actions/mamba-org/provision-with-micromamba/main/dist/main/index.js:64104:3
    at Object.<anonymous> (/home/runner/work/_actions/mamba-org/provision-with-micromamba/main/dist/main/index.js:64107:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```

**Comment by jonashaag** [comment]
Is this a self hosted runner? Can you provide a link to your repo?

**Comment by michaelaye** [comment]
no, it wasn't self-hosted. and sorry, i already developed it away (was a re-usable one so developing was done by re-running the importer, hence no log file remained). 
will try to reproduce and get back to you.

**Comment by jonashaag** [comment]
Any new input here?
